version: '2'

services:
  activemq:
    image: 'docker.io/rmohr/activemq:5.15.9'
    ports:
      - '61616:61616'
      - '8161:8161'
    volumes:
      - './activemq_conf:/opt/activemq/conf'
      - './activemq_data:/opt/activemq/data'
  
volumes:
  activemq_conf:
    driver: local
  activemq_data:
    driver: local